#!/usr/bin/env python3
import sys
import zlib

def main():
    if len(sys.argv ) > 1:
        with open(sys.argv[1], 'rb') as fhandle:
            data = fhandle.read()
    else:
        data = sys.stdin.buffer.read()
    plain = zlib.decompress(data)
    sys.stdout.buffer.write(plain)


if __name__ == "__main__":
    main()
